<template>
  <section
    class="
      w-full
      pt-12
      sm:pt-14
      md:pl-24
      xl:pl-60
      fixed
      bg-white bg-opacity-95
      z-10
    "
  >
    <div class="py-2 px-2 sm:px-4 border-t border-b">
      <div
        class="
          max-w-screen-2xl
          m-auto
          flex
          space-x-3
          overflow-auto
          text-sm
          whitespace-norwap
        "
      >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-600
            border-gray-700
            rounded-full
            transition
            hover:bg-gray-400
            text-white
          "
          >All</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >NBA</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Interview</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Nature</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Moto</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Cars</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Ads</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Films</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Music</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Tech</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >News</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Travelling</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Winter</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Snowboard</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Diving</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Drift</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >RedBull</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Streaming</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Games</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Devs</a
        >
        <a
          href="#"
          class="
            px-3
            py-1
            bg-gray-100
            border-gray-300
            rounded-full
            transition
            hover:bg-gray-200
          "
          >Photos</a
        >
      </div>
    </div>
  </section>
</template>

<script setup>

</script>

<style scoped>

</style>